# Generated by Django 5.2.1 on 2025-05-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
