version: '3.9'

services:
  foodgram_diploma_db:
    image: postgres:15
    container_name: foodgram_diploma_db
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  foodgram_diploma_backend:
    image: 28awg2c/infra-foodgram_diploma_backend:newtag
    container_name: foodgram_diploma_backend
    command: >
      sh -c "/usr/bin/wait-for-it foodgram_diploma_db:5432 -- 
       python manage.py makemigrations --noinput &&
       python manage.py migrate --noinput && \
       python manage.py collectstatic --noinput && \
       gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_data:/work_dir/backend/static
      - media_data:/work_dir/backend/media
      - ../backend/data:/work_dir/backend/data
    depends_on:
      - foodgram_diploma_db
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  foodgram_diploma_frontend:
    image: 28awg2c/infra-foodgram_diploma_frontend:newtag
    container_name: foodgram_diploma_frontend
    command: sh -c "cp -r build/* /frontend_build/ && tail -f /dev/null"
    volumes:
      - frontend_build:/frontend_build

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
      - static_data:/work_dir/backend/static
      - media_data:/work_dir/backend/media
    depends_on:
      - foodgram_diploma_backend
      - foodgram_diploma_frontend


volumes:
  pgdata:
  frontend_build:
  static_data:
  media_data:
