# Generated by Django 5.2.1 on 2025-05-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time_min',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
    ]
