# Generated by Django 5.2.1 on 2025-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0002_rename_cook_time_min_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cooking_time',
        ),
    ]
