# Generated by Django 5.2.1 on 2025-05-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_app', '0003_rename_cook_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='author',
        ),
    ]
