name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat <<EOF > infra/.env
          DB_ENGINE=${{ secrets.DB_ENGINE }}
          DB_NAME=${{ secrets.DB_NAME }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

      - name: Docker Compose
        run: |
          docker compose -f infra/docker-compose.yml up -d --build

      - name: Wait for services
        run: |
          echo "Waiting for services to be up..."
          sleep 30

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run postman_collection/foodgram.postman_collection.json \
            --delay-request 500 \
            --insecure \
            --timeout-request 30000